version: "3.7"
services:

  sam:
    build:
      context: ./docker/sam
    volumes:
      - .:/opt/sam
    working_dir: /opt/sam
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      STACK_NAME: ${STACK_NAME}

  go:
    build:
      context: ./docker/go
    volumes:
      - .:/opt/go
