[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.11.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.20.3"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[prune]
  go-tests = true
  unused-packages = true
