swagger: '2.0'
info:
  title:
    Fn::Sub: ${ProjectName}
  description:
    Fn::Sub: ${ProjectName}
  version: 1.0.0

schemas:
  - https
consumes:
  - application/json
produces:
  - application/json
basePath:
  Fn::Sub: /

paths:
  /v1/face:
    post:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostFace.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

  /v1/auth:
    post:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostAuth.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
